export const original_card = {
    name: "Goblin Queen", // --------------- Name of the card generated by the chatGPT ---------------
    health: 5, // --------------- Chosen by player from the points collection ---------------
    attackPower: 3, // --------------- Chosen by player from the points collection ---------------
    special: "berserk2", // --------------- Chosen by player from the functions collection depending on function rarity ---------------
    imgUrl: "https://cdn.leonardo.ai/users/65dd36eb-c359-4701-a69f-ee6336be912c/generations/5a667bb3-825c-4546-876c-34178097fb17/Character_Portraits_PORTRAIT_CUTE_PIXAR_ANIMATION_STYLE_Good_T_1.jpg", // --------------- Generated by Leonardo AI ---------------
    creator: {
        playerName: "juico199", // --------------- Chosen by player upon onboarding ---------------
        generatedName: "Crescent Rainshadow watcher", // --------------- Generated by inbuild name generator from players wallet address ---------------
        walletAddress: "0x8ca049b20731ff92fe8fc8535531497fb83247fe"
    },
    description: "A wise leader of the caves.", // --------------- Generated by chatGPT ---------------
    type: {
        name: "rare",
        _id: "646f581ab8f70047aff823ba" // --------------- MongoDB object id ---------------
    }, // --------------- Determined by Game Analyzer ---------------
    collection: "bluecrystal"// --------------- (Optional) Depending on Game Analyzer. (Player can create it's own collection that can be listed in the game) ---------------
}